### ISSUE TITLE
Add support for AWS Lambda@Edge

### ISSUE THREAD

**Issue by FxProgrm** [foremast/foremast#344]
It would be beneficial to add support for deploying lambda code through the pipeline that will eventually be assigned to a CloudFront Distribution behavior.  Associating the the necessary IAM Trust Relationships on the role for lambda.amazonaws.com and edgelambda.amazonaws.com would allow for the tooling to do the necessary association.

We attempted to add an update to the lambda_role.json.j2 to include edgelambda.amazonaws.com and re-run the process and noticed that once the role had been created it would not update the existing role with the additional trust relationship.

**Comment by jvasallo** [comment]
Looks like this might be an issue with using S3 Bucket notifications as well.
https://aws.amazon.com/premiumsupport/knowledge-center/lambda-execution-role-s3-bucket/

**Comment by waynetaylor** [comment]
With the evolution of Lambda a change is required to help better define and apply the trust relationship. 

We recentlly learned that when trying to maintain an S3 pipeline with lambda configurations that it failed to be able to apply since the trust relationship didnt exist at the account level. 

This would throw: 
`botocore.exceptions.ClientError: An error occurred (InvalidArgument) when calling the PutBucketNotificationConfiguration operation: Unable to validate the following destination configurations`

Once Trust Relationship was added the generate infrastructure step would work .
