### ISSUE TITLE
Can't find the documentation for lambda accessing EC2 instances

### ISSUE THREAD

**Issue by c0debreaker** [foremast/foremast#393]
I'd like to define a policy like `ec2:DescribeInstances` so that a function in AWS Lambda can run some code that will describe the instance. I don't want to update the IAM Role and Policy directly in AWS console. I'd like to be able to write all the required policies in application-master-{env}.json file. However, I can't find any documentation related to this in Foremast docs.

**Comment by jvasallo** [comment]
Hi there @c0debreaker, that is correct that natively in Foremast we don't ship with any service template for EC2 (yet!). You can see our current supported services here:
https://foremast.readthedocs.io/en/latest/configuration_files/pipeline_json/index.html#services-block

Since we don't support this today, users have two options.
1. Most commonly, end users run their own templates directory to supplement the built in templates. This allows users to define well crafted policies that fit their business needs. The stock policies are rather arbitrary. You can see a sample extension repo here: https://github.com/foremast/foremast-template-examples You define the relative path within your config.py file!

2. I think we can welcome a small simple PR that enables a service such as "ec2ro" which grants ec2:Describe* to your applications. 

Does this help or do you have some ideas/proposal of what you would like to see documented? Treating this as a valid issue as it might expand to other services as well. :)

**Comment by c0debreaker** [comment]
I'll check them out. Thanks a lot @jvasallo!
